# Generated by Django 5.1.4 on 2025-01-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_saveditinerary_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('museum', 'Museum'), ('restaurant', 'Restaurant'), ('market', 'Market'), ('park', 'Park')], max_length=50),
        ),
    ]
